##https://search.nixos.org/packages

[phases.setup]
nixPkgs = ["...", "python311Packages.pip", "python3"]

[phases.build]
nixPkgs = ["...", "pip install requests"]

[phases.test]
cmds = ["""python3 -c 'import requests; print("Requests version:", requests.__version__)'"""]
dependsOn = ["build"]