##https://search.nixos.org/packages

[phases.setup]
nixPkgs = ["...", "python3", "python311Packages.requests"]

[phases.test]
cmds = ["""python3 -c 'import requests; print("Requests version:", requests.__version__)'"""]
dependsOn = ["setup"]