[phases.setup]
nixPkgs = ["...", "python3"]

[phases.build]
cmds = ["...", "pip install -r requirements.txt"]

[phases.test]
cmds = ["""python3 -c 'import requests; print("Requests version:", requests.__version__)'"""]
dependsOn = ["setup"]